const mongoose = require("mongoose");

const todoSchema = new mongoose.Schema({
  text: { type: String, required: true },
  completed: { type: Boolean, default: false },
});

const commentSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    text: {
      type: String,
      required: true,
      trim: true,
      maxlength: 2000,
    },
  },
  { timestamps: true }
);

const taskSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    description: { type: String },
    priority: { type: String, enum: ["Low", "Medium", "High"], default: "Low" },
    status: { type: String, enum: ["Pending", "In Progress", "Completed"], default: "Pending" },
    scope: { type: String, enum: ["team", "self"], default: "team" },
    dueDate: { type: Date, required: true },
    assignedTo: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    attachments: [{ type: String }],
    todoChecklist: [todoSchema],
    comments: [commentSchema],
    tags: [{ type: String, trim: true }],
    progress: { type: Number, default: 0 },
    completedAt: { type: Date, default: null },
    
    // --- AI INTEGRATION FIELDS (Phase 1) ---
    aiSummary: { 
      type: String,
      default: null,
      // One-sentence summary generated by Gemini/Groq
    },
    aiSuggestedTags: [{ type: String, trim: true }],
    // AI-recommended tags for better categorization
    
    complexity: {
      type: String,
      enum: ["Simple", "Medium", "Complex"],
      default: "Medium",
      // AI-assessed task complexity
    },
    
    estimatedHours: {
      type: Number,
      default: null,
      // AI-predicted effort (0.5, 1, 2, 4, 8, 16, etc.)
    },
    
    suggestedSubtasks: [
      {
        text: { type: String, required: true },
        completed: { type: Boolean, default: false },
        estimatedHours: { type: Number, default: 1 },
      }
    ],
    // AI-suggested breakdown of main task
    
    aiAnalysis: {
      priority: { type: String, enum: ["Low", "Medium", "High"], default: null },
      reasoning: { type: String, default: null },
      riskFactors: [{ type: String }],
      successCriteria: [{ type: String }],
      lastAnalyzedAt: { type: Date, default: null },
    },
    // Comprehensive AI analysis with reasoning
    
    lastAISummary: {
      type: Date,
      default: null,
      // Timestamp of last AI summary generation (prevents redundant API calls)
    },
    // ---------------------------
  },
  { timestamps: true }
);

module.exports = mongoose.model("Task", taskSchema);
